# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Mod
mod_id=ecosystem
mod_name=EcoSystem
mod_version=1.0.0
mod_group_id=com.pedrodalben.ecosystem
mod_authors=pedrodalben
mod_description=A complete multi-currency economy system for Minecraft servers
mod_license=MIT

# Minecraft / NeoForge
minecraft_version=1.21.1
neo_version=21.1.172
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17
